default['inventory']['group'] = 'oinstall'
default['inventory']['owner'] = 'oracle'
default['inventory']['oraInst_dir'] = '/home/oracle/responsefile'
default['inventory']['oraInst'] = '/home/oracle/responsefile/oraInst.loc'
default['inventory']['location'] = '/u01/app/oraInventory'
